version: '3'

tasks:
  parse:
    alias: parser
    desc: "Parse is working"
    cmds:
      - echo "Parse is working"
      - go run ./cmd/parser/main.go

  build:
    aliases:
      - b
    desc: "Build app"
    cmds:
      - go build

  build-custom:
    aliases:
      - bc
    desc: "Build app"
    cmds:
      - go build -o sportthunder.exe

  parse-abbr-nhl:
    aliases:
    - pan
    desc: "Parse nhl abbreviations"
    cmds:
      - echo "Parse nhl abbreviations"
      - ./sportthunder nhl --method abbr

  parse-roster-nhl:
    aliases:
    - prnhl
    desc: "Parse nhl roster(debug)"
    cmds:
      - echo "Parse nhl abbreviations"
      - ./sportthunder nhl --method roster

  parse-allroster-nhl:
    aliases:
      - parsnhl
    desc: "Parse nhl roster"
    cmds:
      - echo "Parse nhl abbreviations"
      - ./sportthunder nhl --method allroster